# Generated by Django 5.2.4 on 2025-07-20 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_book_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
    ]
