# Generated by Django 5.2.4 on 2025-07-23 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0004_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
